import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { THEME_FILES } from '../data/themeStructure';

export async function exportThemeZip(onProgress?: (progress: number, currentFile: string) => void) {
  const zip = new JSZip();
  const folder = zip.folder('bumiya-hefazat-gostar');

  if (!folder) {
    throw new Error('Failed to create theme directory inside zip');
  }

  let completed = 0;
  const total = THEME_FILES.length;

  for (const file of THEME_FILES) {
    if (onProgress) {
      onProgress(Math.round((completed / total) * 100), file.path);
    }

    try {
      // In web container or server, we can fetch the file or read it
      const response = await fetch(`/bumiya-hefazat-gostar/${file.path}`);
      if (response.ok) {
        const content = await response.text();
        folder.file(file.path, content);
      } else {
        // Fallback placeholder with standard comment if fetch is not served statically
        folder.file(file.path, `/* Bumiya Hefazat Gostar - ${file.name} */\n/* Generated by Bumiya Architecture Engine */\n`);
      }
    } catch (err) {
      console.warn(`Could not load ${file.path} via fetch, creating fallback entry:`, err);
      folder.file(file.path, `/* Bumiya Hefazat Gostar - ${file.name} */\n`);
    }

    completed++;
  }

  if (onProgress) {
    onProgress(100, 'آماده‌سازی بسته ZIP...');
  }

  const content = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 }
  });

  saveAs(content, 'bumiya-hefazat-gostar-theme.zip');
}
